apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: cagatayakk/demo:latest
        resources:
        ports:
        - containerPort: 80 
      initContainers:
      - name: initcontainer
        image: busybox
        command: ['sh', '-c', "until nc -zvw 1 mycluster 3306; do echo 'Waiting for database_pod'; sleep 2; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: mynodeport
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80

