apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mydb
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P123456p"
        - name: MYSQL_DATABASE
          value: "phonebook"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "Clarusway_1"
        resources:
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mystorage
        - name: first-table
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mystorage
          persistentVolumeClaim:
            claimName: mypvc
        - name: first-table
          configMap:
            name: myconfigmap
---
apiVersion: v1
kind: Service
metadata:
  name: mycluster
spec:
  type: ClusterIP
  selector:
    app: mydb
  ports:
  - port: 3306
    targetPort: 3306

