apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: httpd
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/local/apache2/htdocs"
          name: mystorage

      volumes:
        - name: mystorage
          persistentVolumeClaim:
            claimName: mypvc
