apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UEBzc3cwcmQyIQ==
  MYSQL_DATABASE: d29yZHByZXNzZGI=
  MYSQL_USER: bXlzcWx3cGFkbWlu
  MYSQL_PASSWORD: UEBzc3cwcmQxIQ==
  
  
